name: Sync Repo to GitLab of RPTU

on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: keninkujovic/gitlab-sync@2.0.0
      with:
        gitlab_url: ${{ secrets.GITLAB_URL }}
        username: ${{ secrets.USERNAME_GITLAB }}
        gitlab_pat: ${{ secrets.GITLAB_PAT }}
